import { createApp } from "vue";
import { createPinia } from "pinia";
import VueKonva from "vue-konva";
import { createI18n } from "vue-i18n";
import App from "./App.vue";
import { platformKey, resolvePlatform } from "./platform";
import "./styles.css";

const savedLocale = localStorage.getItem("imagetoolbox.locale");
const systemLocale = navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";

const i18n = createI18n({
  legacy: false,
  locale: savedLocale || systemLocale,
  fallbackLocale: "en",
  messages: {
    zh: {
      select: "选择",
      import: "导入图片",
      crop: "裁剪",
      text: "文本",
      rectangle: "矩形",
      ellipse: "椭圆",
      line: "直线",
      arrow: "箭头",
      pen: "画笔",
      highlighter: "荧光笔",
      pan: "平移",
      shortcuts: {
        select: "V",
        import: "Ctrl/⌘+O",
        crop: "C",
        text: "T",
        rectangle: "R",
        pen: "P",
        pan: "空格",
        undo: "Ctrl/⌘+Z",
        redo: "Ctrl/⌘+Shift+Z",
        save: "Ctrl/⌘+S",
        export: "Ctrl/⌘+E",
      },
      topbar: {
        rename: "重命名工程",
        renameHint: "点击重命名工程",
        projectName: "工程名称",
        undo: "撤销",
        redo: "重做",
        import: "导入",
        open: "打开",
        save: "保存工程",
        switchLanguage: "切换到英文",
        export: "导出",
      },
      mobile: {
        properties: "属性",
        layers: "图层",
        tools: "编辑工具",
      },
      status: {
        zoomOut: "缩小",
        zoom: "缩放",
        zoomIn: "放大",
        fit: "适应",
        localOnly: "仅在本地处理",
      },
      canvas: {
        empty: "画布还是空的",
        opening: "正在打开…",
        openTestProject: "打开测试工程",
        cropMode: "裁剪模式",
        placeText: "单击画布放置文本",
        drawShape: "拖动绘制{shape} · 按住 Shift 绘制{lockedShape}",
        square: "正方形",
        circle: "圆形",
      },
      exportDialog: {
        title: "导出图片",
        description: "使用原始图片资源合成最终结果",
        close: "关闭",
        format: "格式",
        scale: "倍率",
        quality: "质量",
        selectionOnly: "仅导出选中对象",
        nothing: "没有可导出的可见内容",
        jpgWarning: "JPG 不支持透明背景，将自动填充为白色。",
        cancel: "取消",
        exporting: "正在导出…",
        export: "导出",
      },
      inspector: {
        label: "属性和图层",
        close: "关闭面板",
        crop: "裁剪",
        ratio: "比例",
        free: "自由",
        original: "原图",
        cropArea: "裁剪区域",
        width: "宽",
        height: "高",
        zoomContent: "缩放图片内容",
        cropHelp: "拖动滑块调整可见区域。裁剪不会修改原始图片内容。",
        reset: "重置",
        cancel: "取消",
        done: "完成",
        properties: "属性",
        position: "位置",
        size: "大小",
        rotation: "旋转",
        opacity: "不透明度",
        border: "边框",
        cornerRadius: "圆角",
        stroke: "描边",
        strokeColor: "描边颜色",
        strokeWidth: "描边宽度",
        fill: "填充",
        fillColor: "填充颜色",
        fillOpacity: "填充不透明度",
        line: "线条",
        lineColor: "线条颜色",
        lineWidth: "线条宽度",
        text: "文字",
        fontSize: "字号",
        color: "颜色",
        textColor: "文字颜色",
        backgroundLayer: "背景图层",
        visible: "显示背景",
        locked: "锁定背景",
        autoSize: "自适应大小",
        backgroundSize: "背景尺寸",
        transformBackground: "在画布中拖动/缩放",
        transformBackgroundHint: "可直接拖动背景，并使用控制点调整大小。",
        transformBackgroundLockedHint: "背景已锁定，尺寸、拖动和缩放均不可修改。",
        canvasWidth: "画布宽度",
        canvasHeight: "画布高度",
        apply: "应用尺寸",
        swap: "交换宽高",
        transparent: "透明背景",
        background: "背景颜色",
        layers: "图层",
        layerCount: "{count} 个图层",
        moveUp: "上移",
        moveDown: "下移",
        resizePanels: "调整属性和图层面板高度",
        dragLayer: "拖动调整图层顺序",
        layerDragLabel: "{name}，拖动可调整图层顺序",
        moveUpTitle: "将当前图层上移一层",
        moveDownTitle: "将当前图层下移一层",
        square: "方形",
        landscape: "横屏 16:9",
        portrait: "竖屏 9:16",
        social: "社交媒体 4:5",
      },
      options: {
        settings: "{tool}设置",
        hint: "应用于下一个对象，不会修改当前选中内容。",
        restoreDefaults: "恢复默认值",
        reset: "重置",
        defaultText: "默认文字",
        fontSize: "字号",
        textWidth: "文本框宽度",
        weight: "字重",
        regular: "常规",
        medium: "中等",
        semibold: "半粗",
        bold: "粗体",
        extrabold: "特粗",
        align: "对齐",
        alignLeft: "左对齐",
        alignCenter: "居中",
        alignRight: "右对齐",
        textColor: "文字颜色",
        stroke: "描边",
        style: "线型",
        solid: "实线",
        dashed: "虚线",
        fill: "填充",
        cornerRadius: "圆角",
        line: "线条",
        arrowhead: "箭头大小",
        strokeWidth: "笔触粗细",
        strokeColor: "笔触颜色",
        opacity: "不透明度",
      },
    },
    en: {
      select: "Select",
      import: "Import",
      crop: "Crop",
      text: "Text",
      rectangle: "Rectangle",
      ellipse: "Ellipse",
      line: "Line",
      arrow: "Arrow",
      pen: "Pen",
      highlighter: "Highlighter",
      pan: "Pan",
      shortcuts: {
        select: "V",
        import: "Ctrl/⌘+O",
        crop: "C",
        text: "T",
        rectangle: "R",
        pen: "P",
        pan: "Space",
        undo: "Ctrl/⌘+Z",
        redo: "Ctrl/⌘+Shift+Z",
        save: "Ctrl/⌘+S",
        export: "Ctrl/⌘+E",
      },
      topbar: {
        rename: "Rename project",
        renameHint: "Click to rename project",
        projectName: "Project name",
        undo: "Undo",
        redo: "Redo",
        import: "Import",
        open: "Open",
        save: "Save Project",
        switchLanguage: "切换到中文",
        export: "Export",
      },
      mobile: {
        properties: "Properties",
        layers: "Layers",
        tools: "Editing tools",
      },
      status: {
        zoomOut: "Zoom out",
        zoom: "Zoom",
        zoomIn: "Zoom in",
        fit: "Fit",
        localOnly: "Processed locally",
      },
      canvas: {
        empty: "The canvas is empty",
        opening: "Opening…",
        openTestProject: "Open Test Project",
        cropMode: "Crop mode",
        placeText: "Click the canvas to place text",
        drawShape: "Drag to draw a {shape} · Hold Shift for a {lockedShape}",
        square: "square",
        circle: "circle",
      },
      exportDialog: {
        title: "Export Image",
        description: "Compose the final image from the original assets",
        close: "Close",
        format: "Format",
        scale: "Scale",
        quality: "Quality",
        selectionOnly: "Selection only",
        nothing: "No visible content to export",
        jpgWarning: "JPG does not support transparency; white will be used instead.",
        cancel: "Cancel",
        exporting: "Exporting…",
        export: "Export",
      },
      inspector: {
        label: "Properties and layers",
        close: "Close panel",
        crop: "Crop",
        ratio: "Ratio",
        free: "Free",
        original: "Original",
        cropArea: "Crop area",
        width: "Width",
        height: "Height",
        zoomContent: "Scale image content",
        cropHelp: "Drag the slider to adjust the visible area. Cropping preserves the original image.",
        reset: "Reset",
        cancel: "Cancel",
        done: "Done",
        properties: "Properties",
        position: "Position",
        size: "Size",
        rotation: "Rotation",
        opacity: "Opacity",
        border: "Border",
        cornerRadius: "Corner radius",
        stroke: "Stroke",
        strokeColor: "Stroke color",
        strokeWidth: "Stroke width",
        fill: "Fill",
        fillColor: "Fill color",
        fillOpacity: "Fill opacity",
        line: "Line",
        lineColor: "Line color",
        lineWidth: "Line width",
        text: "Text",
        fontSize: "Font size",
        color: "Color",
        textColor: "Text color",
        backgroundLayer: "Background layer",
        visible: "Show background",
        locked: "Lock background",
        autoSize: "Auto size",
        backgroundSize: "Background size",
        transformBackground: "Drag/resize on canvas",
        transformBackgroundHint: "Drag the background or use its handles to resize it.",
        transformBackgroundLockedHint: "The background is locked; its size, position, and scale cannot be changed.",
        canvasWidth: "Canvas width",
        canvasHeight: "Canvas height",
        apply: "Apply size",
        swap: "Swap width/height",
        transparent: "Transparent background",
        background: "Background color",
        layers: "Layers",
        layerCount: "{count} layer(s)",
        moveUp: "Move up",
        moveDown: "Move down",
        resizePanels: "Resize properties and layers panels",
        dragLayer: "Drag to reorder layer",
        layerDragLabel: "{name}, drag to reorder",
        moveUpTitle: "Move current layer up",
        moveDownTitle: "Move current layer down",
        square: "Square",
        landscape: "Landscape 16:9",
        portrait: "Portrait 9:16",
        social: "Social media 4:5",
      },
      options: {
        settings: "{tool} Settings",
        hint: "Applies to the next object without changing the current selection.",
        restoreDefaults: "Restore defaults",
        reset: "Reset",
        defaultText: "Default text",
        fontSize: "Font size",
        textWidth: "Text box width",
        weight: "Weight",
        regular: "Regular",
        medium: "Medium",
        semibold: "Semibold",
        bold: "Bold",
        extrabold: "Extra bold",
        align: "Align",
        alignLeft: "Left",
        alignCenter: "Center",
        alignRight: "Right",
        textColor: "Text color",
        stroke: "Stroke",
        style: "Style",
        solid: "Solid",
        dashed: "Dashed",
        fill: "Fill",
        cornerRadius: "Corner radius",
        line: "Line",
        arrowhead: "Arrowhead",
        strokeWidth: "Stroke width",
        strokeColor: "Stroke color",
        opacity: "Opacity",
      },
    },
  },
});

const app = createApp(App);
app.use(createPinia());
app.use(i18n);
app.use(VueKonva);
app.provide(platformKey, resolvePlatform());
app.mount("#app");
